- name: Update Ubuntu packages
  hosts: all
  become: 'True'
  tasks:
    - name: Update cache
      apt:
        update_cache: yes

    - name: Upgrade all packages on servers
      async: 800
      poll: 05
      apt:
        name: "*"
        state: latest
